/**
 * TeamRoster — the "team" section from the leader microsite page.
 *
 * Ports `leader.html > section.team` (markup at ~line 487) plus the inline
 * script that fills `#tgrid` at runtime (~line 637). The static markup is only
 * the shell; every roster card is generated by JS, so the card DOM below
 * mirrors that generated structure exactly —
 *
 *   section.team                     32px top / 96px bottom
 *     div.seyebrow.sreveal           accent eyebrow, 28×2 leading rule
 *     div.team-head.sreveal          flex row, baseline-aligned, wraps
 *       h2                           clamp(26px, 3vw, 38px), extrabold
 *       span.team-meta               "<b>N</b> direct reports · <b>N</b> in the org"
 *     div.tgrid                      3 cols → 2 (≤880px) → 1 (≤560px), 14px gap
 *       div.tcard                    avatar + name/role/badge, 18px radius, 94px min-height
 *         img.tav | div.tav          56px circle — photo, else tinted initials
 *         div.twho
 *           div.tname                17px bold
 *           div.trole               13.5px muted
 *           span.tbadge              accent pill: people icon + "Manages <b>N</b>"
 *
 * Motion, reproduced from the source:
 *   • `.sreveal` head elements start at opacity 0 / translateY(34px) and settle
 *     with `opacity 1s ease, transform 1.15s var(--ease-spring)`, staggered
 *     0s and 0.08s.
 *   • `.tcard`s start at opacity 0 / translateY(26px) and settle with
 *     `transform 1s var(--ease-spring), opacity .85s ease`, staggered 90ms per
 *     card (`card.style.transitionDelay = (i * 90) + 'ms'`).
 *   • Reveal is driven by an IntersectionObserver with the source's
 *     `rootMargin: '0px 0px -15% 0px'` trigger line.
 *   • The two `.count` numerals tick up from 0 with an ease-out-cubic over
 *     1100ms once the section reveals (source: `countUp`, 1100ms, `1 - (1-p)^3`).
 *   • `prefers-reduced-motion` or `animate={false}` renders the settled state
 *     and the final numerals immediately — same as the source's `reduce` branch.
 *
 * All names, photos, roles and headcounts are placeholders; pass real data in.
 */

/* Muted avatar tints used when a member has no photo. Picked by summing the
   name's char codes, exactly like the source's `colorFor()`. */
const TR_AVATAR_TINTS = [
  '#5b6b7b',
  '#3f7d6e',
  '#9a6a3a',
  '#5a5a8e',
  '#7a5a6e',
  '#4a7a8c',
  '#7b6f4a',
];

function trTintFor(name) {
  const s = String(name || '')
    .split('')
    .reduce((acc, ch) => acc + ch.charCodeAt(0), 0);
  return TR_AVATAR_TINTS[s % TR_AVATAR_TINTS.length];
}

function trInitials(name) {
  const parts = String(name || '')
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0]);
  return parts.join('').toUpperCase() || '?';
}

/* The source's `P_ICON` — two-person glyph inside the "Manages" pill. */
const TR_PEOPLE_ICON = (
  <svg
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2.2"
    strokeLinecap="round"
    strokeLinejoin="round"
    aria-hidden="true"
    style={{ width: 13, height: 13, flex: 'none' }}
  >
    <path d="M16 19v-1a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v1" />
    <circle cx="9" cy="7" r="3.2" />
    <path d="M22 19v-1a4 4 0 0 0-3-3.87" />
    <path d="M16 3.5a4 4 0 0 1 0 7" />
  </svg>
);

const TR_DEFAULT_MEMBERS = [
  {
    name: 'Team Member One',
    title: 'Role title goes here',
    avatar: '../../faces/placeholders/avatar-01.svg',
    manages: 6,
  },
  {
    name: 'Team Member Two',
    title: 'Role title goes here',
    avatar: '../../faces/placeholders/avatar-02.svg',
    manages: 0,
  },
  {
    name: 'Team Member Three',
    title: 'Role title goes here',
    avatar: '../../faces/placeholders/avatar-03.svg',
    manages: 4,
  },
  {
    name: 'Team Member Four',
    title: 'Role title goes here',
    avatar: '../../faces/placeholders/avatar-04.svg',
    manages: 0,
  },
  {
    name: 'Team Member Five',
    title: 'Role title goes here',
    avatar: '../../faces/placeholders/avatar-05.svg',
    manages: 3,
  },
  {
    name: 'Team Member Six',
    title: 'Role title goes here',
    avatar: '../../faces/placeholders/avatar-06.svg',
    manages: 0,
  },
];

const TR_FALLBACK_HEADING_ID = () => 'team-roster-heading';

/**
 * Ticking numeral. Counts 0 → `value` over 1100ms with the source's
 * ease-out-cubic; renders `value` outright when `run` is false.
 */
function TeamRosterCount({ value, run }) {
  const target = Number(value) || 0;
  const [n, setN] = React.useState(run ? 0 : target);

  React.useEffect(() => {
    if (!run) {
      setN(target);
      return undefined;
    }
    let raf = 0;
    let start = null;
    const dur = 1100;
    const step = (t) => {
      if (start === null) start = t;
      const p = Math.min(1, (t - start) / dur);
      const e = 1 - Math.pow(1 - p, 3);
      setN(Math.round(target * e));
      if (p < 1) raf = requestAnimationFrame(step);
    };
    raf = requestAnimationFrame(step);
    return () => cancelAnimationFrame(raf);
  }, [run, target]);

  return (
    <b
      style={{
        color: 'var(--ink)',
        fontWeight: 'var(--fw-extrabold)',
        fontVariantNumeric: 'tabular-nums',
      }}
    >
      {n}
    </b>
  );
}

/** One roster card — `.tcard` from the generated markup. */
function TeamRosterCard({ member, index, shown, managesLabel }) {
  const [imgFailed, setImgFailed] = React.useState(false);
  const manages = Number(member.manages) || 0;
  const hasPhoto = Boolean(member.avatar) && !imgFailed;

  const avatarBase = {
    flex: 'none',
    width: 56,
    height: 56,
    borderRadius: 'var(--radius-circle)',
    display: 'grid',
    placeItems: 'center',
    color: '#fff',
    fontWeight: 'var(--fw-bold)',
    fontSize: 17,
    letterSpacing: '0.01em',
    userSelect: 'none',
    objectFit: 'cover',
  };

  return (
    <li
      style={{
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--space-4)',
        background: 'var(--bg, #fff)',
        /* No neutral token sits at this weight — --line (#ececef) is visibly
           lighter than the source's card border, so the literal is kept. */
        border: '1px solid #d7d7dd',
        borderRadius: 18,
        padding: '18px 20px',
        minHeight: 94,
        boxShadow: 'var(--shadow-sm)',
        opacity: shown ? 1 : 0,
        transform: shown ? 'none' : 'translateY(26px)',
        transition: 'transform 1s var(--ease-spring), opacity .85s ease',
        transitionDelay: `${index * 90}ms`,
        willChange: 'opacity, transform',
      }}
    >
      {hasPhoto ? (
        <img
          src={member.avatar}
          alt={member.name}
          loading="lazy"
          decoding="async"
          onError={() => setImgFailed(true)}
          style={avatarBase}
        />
      ) : (
        <div style={{ ...avatarBase, background: trTintFor(member.name) }} aria-hidden="true">
          {trInitials(member.name)}
        </div>
      )}

      <div style={{ minWidth: 0, flex: 1 }}>
        <div
          style={{
            fontSize: 17,
            fontWeight: 'var(--fw-bold)',
            letterSpacing: '-0.01em',
            lineHeight: 1.16,
          }}
        >
          {member.name}
        </div>
        <div
          style={{
            fontSize: 13.5,
            color: 'var(--muted)',
            marginTop: 3,
            lineHeight: 1.3,
          }}
        >
          {member.title}
        </div>
        {manages > 0 && (
          <span
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 6,
              marginTop: 9,
              fontSize: 12.5,
              fontWeight: 'var(--fw-bold)',
              color: 'var(--accent)',
              background: 'var(--accent-soft)',
              padding: '4px 10px 4px 8px',
              borderRadius: 'var(--radius-pill)',
              lineHeight: 1,
            }}
          >
            {TR_PEOPLE_ICON}
            {managesLabel} <b style={{ fontWeight: 'var(--fw-extrabold)' }}>{manages}</b>
          </span>
        )}
      </div>
    </li>
  );
}

export function TeamRoster({
  eyebrow = 'Section eyebrow',
  title = 'Team headline goes here',
  members = TR_DEFAULT_MEMBERS,
  directCount,
  orgCount,
  directLabel = 'direct reports',
  orgLabel = 'in the org',
  managesLabel = 'Manages',
  showMeta = true,
  animate = true,
  headingId,
}) {
  const list = Array.isArray(members) ? members : [];

  /* Source: metaDirect = L.reports.length, metaOrg = the team's total headcount.
     Both derive from the roster unless explicitly supplied. */
  const directTotal = directCount != null ? Number(directCount) : list.length;
  const orgTotal =
    orgCount != null
      ? Number(orgCount)
      : list.reduce((sum, m) => sum + (Number(m && m.manages) || 0), list.length);

  const sectionRef = React.useRef(null);
  const [shown, setShown] = React.useState(!animate);
  const [counting, setCounting] = React.useState(false);
  const autoId = (React.useId || TR_FALLBACK_HEADING_ID)();
  const h2Id = headingId || autoId;

  React.useEffect(() => {
    if (!animate) {
      setShown(true);
      setCounting(false);
      return undefined;
    }
    const el = sectionRef.current;
    const reduce =
      typeof window !== 'undefined' &&
      typeof window.matchMedia === 'function' &&
      window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (!el || reduce || typeof IntersectionObserver === 'undefined') {
      setShown(true);
      setCounting(false);
      return undefined;
    }
    /* Same trigger line as the source's revealCards(): pulled up 15% from the
       viewport bottom so the section animates once it is comfortably on screen. */
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setShown(true);
            setCounting(true);
            io.disconnect();
          }
        });
      },
      { rootMargin: '0px 0px -15% 0px' }
    );
    io.observe(el);
    return () => io.disconnect();
  }, [animate]);

  /* `.sreveal` — opacity 0 / translateY(34px) until revealed. */
  const reveal = (delay) => ({
    opacity: shown ? 1 : 0,
    transform: shown ? 'none' : 'translateY(34px)',
    transition: 'opacity 1s ease, transform 1.15s var(--ease-spring)',
    transitionDelay: `${delay}s`,
    willChange: 'opacity, transform',
  });

  return (
    <section
      ref={sectionRef}
      aria-labelledby={h2Id}
      style={{ padding: 'var(--space-8) 0 var(--space-24)' }}
    >
      {/* Responsive column counts can't be expressed inline — and must not be set
          inline either, or the media queries below could never win. */}
      <style>{`
        .ds-troster-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 14px;
          margin: 0;
          padding: 0;
          list-style: none;
        }
        @media (max-width: 880px) {
          .ds-troster-grid { grid-template-columns: repeat(2, 1fr); }
        }
        @media (max-width: 560px) {
          .ds-troster-grid { grid-template-columns: 1fr; }
        }
      `}</style>

      {eyebrow && (
        <div
          style={{
            ...reveal(0),
            fontSize: 'var(--text-sm)',
            fontWeight: 'var(--fw-bold)',
            letterSpacing: 'var(--ls-caps)',
            textTransform: 'uppercase',
            color: 'var(--accent)',
            display: 'inline-flex',
            alignItems: 'center',
            gap: 12,
            margin: '0 0 14px',
          }}
        >
          <span
            aria-hidden="true"
            style={{
              width: 28,
              height: 2,
              background: 'var(--accent)',
              borderRadius: 2,
              display: 'inline-block',
            }}
          />
          {eyebrow}
        </div>
      )}

      <div
        style={{
          ...reveal(0.08),
          display: 'flex',
          alignItems: 'baseline',
          justifyContent: 'space-between',
          gap: 'var(--space-6)',
          margin: '0 0 var(--space-5)',
          flexWrap: 'wrap',
        }}
      >
        <h2
          id={h2Id}
          style={{
            fontSize: 'clamp(26px, 3vw, 38px)',
            fontWeight: 'var(--fw-extrabold)',
            letterSpacing: 'var(--ls-tighter)',
            margin: 0,
          }}
        >
          {title}
        </h2>
        {showMeta && (
          <span
            style={{
              fontSize: 'var(--text-base)',
              color: 'var(--muted)',
              fontWeight: 'var(--fw-medium)',
              whiteSpace: 'nowrap',
            }}
          >
            <TeamRosterCount value={directTotal} run={counting} /> {directLabel}
            {' · '}
            <TeamRosterCount value={orgTotal} run={counting} /> {orgLabel}
          </span>
        )}
      </div>

      <ul className="ds-troster-grid">
        {list.map((member, i) => (
          <TeamRosterCard
            key={`${member.name || 'member'}-${i}`}
            member={member}
            index={i}
            shown={shown}
            managesLabel={managesLabel}
          />
        ))}
      </ul>
    </section>
  );
}
